Di lin/hw2
TAIsRich/chuwa1010 pull request #40
Opened 2022-10-14 18:36 UTC by Lin27604

2022-10-17 02:49 UTC, CharlesCCC requested changes

2022-10-17 02:49 UTC, CharlesCCC commented on ShortQuestions/hw1
> +  Learn MarkDown and show all of basic usage in the ShortQuestions/README.md
this is not a markdown file , please fix it up.

2022-10-18 03:11 UTC, Lin27604 commented on ShortQuestions/hw1
> +  Learn MarkDown and show all of basic usage in the ShortQuestions/README.md
是因为我加有两个横杠在答案面前么

2022-10-18 03:15 UTC, CharlesCCC commented on ShortQuestions/hw1
> +  Learn MarkDown and show all of basic usage in the ShortQuestions/README.md
不是,你的file extension都不是 `.md`

2022-10-24 06:23 UTC, TAIsRich commented
conflicts

2022-10-25 02:19 UTC, merged